project/src/Entity/Play.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Idk\LegoBundle\Annotation\Entity as Lego;
use Symfony\Component\Validator\Constraints\NotBlank;
use App\Entity\Collection as PlayCollection;

/**
 * Jeu
 *
 * @Lego\Entity(
 *     config="App\Configurator\PlayConfigurator",
 *     title="Jeu",
 *     permissions={"edit"="ROLE_USER"})
 * @ORM\Table(name="jeu")
 * @ORM\Entity(repositoryClass="App\Repository\PlayRepository")
 * @Lego\EntityExport(fields={"id", "name"})
 */
class Play
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     * @Lego\Field(label="Nom",path="show", edit_in_place=false, sort=true)
     * @Lego\Filter\StringFilter()
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="position", type="string", length=2, nullable=true)
     */
    private $position;


    /**
     * @var int
     *
     * @ORM\Column(name="nbPlayerMin", type="integer")
     * @Lego\Field(label="Nombre de joueurs min", edit_in_place=true)
     * //@Lego\Filter\NumberRangeFilter()
     */
    private $nbPlayerMin;

    /**
     * @var int
     *
     * @ORM\Column(name="nbPlayerMax", type="integer")
     * @Lego\Field(label="Nombre de joueurs max", edit_in_place=true)
     * //@Lego\Filter\NumberRangeFilter()
     */
    private $nbPlayerMax;

    /**
     * @var int
     *
     * @ORM\Column(name="nbPlayerAdvisorMin", type="integer")
     * @Lego\Field(label="Nombre conseillé min")
     * //@Lego\Filter\NumberRangeFilter()
     */
    private $nbPlayerAdvisorMin;

    /**
     * @var int
     *
     * @ORM\Column(name="nbPlayerAdvisorMax", type="integer")
     * @Lego\Field(label="Nombre conseillé max")
     * //@Lego\Filter\NumberRangeFilter()
     */
    private $nbPlayerAdvisorMax;

    /**
     * @var int
     *
     * @ORM\Column(name="note", type="integer", nullable=true)
     * //@Lego\Field(label="Note")
     * //@Lego\Form\NoteForm(max=3)
     * @Lego\Filter\NumberRangeFilter()
     */
    private $note;

    /**
     * @var int
     * @Lego\Field(label="Age")
     * @ORM\Column(name="age", type="integer", nullable=true)
     */
    private $age;

    /**
     * @var Author
     *
     * @ORM\ManyToMany(targetEntity="Category")
     * //@Lego\Form\EntityForm(class="App\Entity\Category", multiple=true)
     * //@Lego\Field(label="Catégorie", edit_in_place=false)
     * @ORM\JoinColumn(name="author_id", referencedColumnName="id")
     */
    private $categories;

    /**
     * @var Editor
     *
     * @ORM\ManyToOne(targetEntity="Editor")
     * @Lego\Field(label="Editeur",  edit_in_place={"reload":"field"}, path={"route":"app_backend_editorlego_show", "params"={"id":"editor.id"}})
     * @ORM\JoinColumn(name="editeur_id", referencedColumnName="id")
     */
    private $editor;




    /**
     * @var string
     *
     * @Lego\File(directory="public/uploads/play")
     * @Lego\Form\FileForm()
     * @Lego\Field(label="Image", image={"directory":"/uploads/play","width":"100px"})
     * @ORM\Column(name="pictur", type="string", nullable=true)
     */
    private $pictur;

    /**
     * @var string
     *
     * @Lego\File(directory="public/uploads/playlogo")
     * @Lego\Form\FileForm()
     * @Lego\Field(label="Logo", image={"directory":"/uploads/playlogo","width":"80px"})
     * @ORM\Column(name="logo", type="string", nullable=true)
     */
    private $logo;

    /**
     * @var string
     *
     * @Lego\Field(label="Description")
     * @Lego\Form\WysihtmlForm()
     * @ORM\Column(name="description", type="text")
     * @NotBlank()
     */
    private $description;


    /**
     * @var ArrayCollection
     *
     * //@Lego\Field(label="Durées")
     * //@Lego\Form\CollectionForm(entity="App\Entity\LiaisonPlayDuration")
     * //@Lego\Form\ManyToManyJoinForm(entity="App\Entity\LiaisonPlayDuration")
     * @ORM\OneToMany(targetEntity="App\Entity\LiaisonPlayDuration",orphanRemoval=true, mappedBy="play", cascade={"persist","remove"})
     */
    private $durations;

    /**
     * @Lego\Field(label="Genres")
     * @Lego\Form\EntityForm(class="App\Entity\Genre", multiple=true)
     * @ORM\ManyToMany(targetEntity="App\Entity\Genre")
     */
    private $genres;

    /**
     * @Lego\Field(label="Thèmes")
     * //@Lego\Filter\EntityFilter(table="App\Entity\Theme")
     * @Lego\Form\EntityForm(class="App\Entity\Theme", multiple=true)
     * @ORM\ManyToMany(targetEntity="App\Entity\Theme")
     */
    private $themes;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Duration")
     * @Lego\Field(label="Durée")
     */
    private $duration;

    /**
     * @Lego\Form\ManyToManyJoinForm(entity="App\Entity\PlayerOfPlay", label="Notes/Joueurs")
     * @ORM\OneToMany(targetEntity="App\Entity\PlayerOfPlay", mappedBy="play", orphanRemoval=true, cascade={"persist","remove"})
     */
    private $players;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\PlayComment", mappedBy="play")
     * @ORM\OrderBy({"createdAt" = "DESC"})
     */
    private $playComments;

    /**
     * @Lego\Form\EntityForm(class="App\Entity\Play", label="Nécessite", required=false)
     * @ORM\ManyToOne(targetEntity="App\Entity\Play", inversedBy="extensions")
     * @ORM\JoinColumn(nullable=true)
     */
    private $requirement;

    /**
     * @Lego\Form\EntityForm(class="App\Entity\Play", multiple=true, label="Extensions", required=false, by_reference=false)
     * @ORM\OneToMany(targetEntity="App\Entity\Play", mappedBy="requirement", cascade={"persist"})
     */
    private $extensions;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Collection", inversedBy="plays")
     * @Lego\Field(label="Collections", edit_in_place=false)
     * //@Lego\Filter\EntityFilter(table="App\Entity\Collection")
     * @Lego\Form\EntityForm(class="App\Entity\Collection", multiple=true, by_reference=false)
     */
    private $collections;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Lego\Field(label="Video")
     */
    private $video;



    public function __construct()
    {
        $this->durations = new ArrayCollection();
        $this->categories = new ArrayCollection();
        $this->genres = new ArrayCollection();
        $this->themes = new ArrayCollection();
        $this->players = new ArrayCollection();
        $this->playComments = new ArrayCollection();
        $this->extensions = new ArrayCollection();
        $this->collections = new ArrayCollection();
    }

    public function __toString(){
        return $this->getName();
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Jeu
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }


    /**
     * Get nbPlayer
     *
     * @return string
     */
    public function getNbPlayer()
    {
        if($this->nbPlayerMin && $this->nbPlayerMax) {
            if($this->nbPlayerMin === $this->nbPlayerMax) return $this->nbPlayerMax;
            return $this->nbPlayerMin . ' - ' . $this->nbPlayerMax;
        }
        return $this->nbPlayerMax ?? $this->nbPlayerMin;
    }

    /**
     * @return string
     */
    public function getNbPlayerAdvisor()
    {
        if($this->nbPlayerAdvisorMin && $this->nbPlayerAdvisorMax) {
            if($this->nbPlayerAdvisorMin === $this->nbPlayerAdvisorMax) return $this->nbPlayerAdvisorMax;
            return $this->nbPlayerAdvisorMin . ' - ' . $this->nbPlayerAdvisorMax;
        }
        return $this->nbPlayerAdvisorMax ?? $this->nbPlayerAdvisorMin;
    }


    /**
     * Set age
     *
     * @param integer $age
     *
     * @return Jeu
     */
    public function setAge($age)
    {
        $this->age = $age;

        return $this;
    }

    /**
     * Get age
     *
     * @return int
     */
    public function getAge()
    {
        return $this->age;
    }

    /**
     * @return Editor
     */
    public function getEditor(): ?Editor
    {
        return $this->editor;
    }

    /**
     * @param Editor $editor
     */
    public function setEditor(Editor $editor): void
    {
        $this->editor = $editor;
    }

    /**
     * @return Author
     */
    public function getCategories()
    {
        return $this->categories;
    }

    /**
     * @param Author $category
     */
    public function setCategories($categories)
    {
        $this->categories = $categories;
    }

    /**
     * @return int
     */
    public function getPictur()
    {
        return $this->pictur;
    }

    /**
     * @param int $pictur
     */
    public function setPictur($pictur)
    {
        if($pictur) {
            $this->pictur = $pictur;
        }
    }

    /**
     * @return int
     */
    public function getLogo()
    {
        return $this->logo;
    }

    /**
     * @param int $logo
     */
    public function setLogo($logo)
    {
        if($logo) {
            $this->logo = $logo;
        }
    }

    /**
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param string $description
     */
    public function setDescription(?string $description)
    {
        $this->description = $description;
    }

    /**
     * @return ArrayCollection
     */
    public function getDurations()
    {
        return $this->durations;
    }

    /**

     * @param ArrayCollection $durations
     */
    public function setDurations($durations): void
    {

project/src/Controller/Backend/DefaultController.php
<?php
namespace App\Controller\Backend;


use Idk\LegoBundle\Controller\AbstractLegoController;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class DefaultController extends AbstractLegoController {



}

project/src/Controller/Frontend/CollectionController.php
<?php
namespace App\Controller\Frontend;

use App\Entity\Collection;
use App\Entity\Play;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class CollectionController extends AbstractController {



    private $em;
    private $paginator;

    public function __construct(EntityManagerInterface $em, PaginatorInterface $paginator)
    {
        $this->em = $em;
        $this->paginator = $paginator;
    }

    /**
 * @Route("/my/collection/{id}/{page}", name="collection_index", defaults={"page":1})
 */
    public function index(Request $request, Collection $collection, $page)
    {
        $pagination = $this->paginator->paginate(
            $this->em->getRepository(Play::class)->getQueryBuilderByFilter($request->getSession()->get('filter', []), $collection)->getQuery(),
            $page ?? 1,
            30
        );
        return $this->render('Frontend/Collection/list.html.twig', [
            'page' => $pagination,
            'collection' => $collection,
            'filter' => $request->getSession()->get('filter', [])
        ]);
    }

    /**
     * @Route("/my/collection/{id}/play/{idp}", name="collection_play")
     */
    public function play(Request $request, Collection $collection)
    {
        return $this->render('Frontend/Collection/play.html.twig', [
            'play' => $this->em->getRepository(Play::class)->find($request->get('idp')),
            'collection' => $collection
        ]);
    }

}

project/src/Controller/Frontend/DefaultController.php
<?php
namespace App\Controller\Frontend;

use App\Entity\Play;
use App\Form\ContactType;
use App\Form\Filter\PlayFilterType;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class DefaultController extends AbstractController {


    private $em;
    private $paginator;

    public function __construct(EntityManagerInterface $em, PaginatorInterface $paginator)
    {
        $this->em = $em;
        $this->paginator = $paginator;
    }

    /**
     * @Route("/{page}", requirements={"page":"\d+"},name="homepage", defaults={"page":1})
     */
    public function index(Request $request, $page)
    {


        $form = $this->createForm(PlayFilterType::class);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $page = 1;
            if($request->request->has('erase')){
                $request->getSession()->set('filter', []);
            }else {
                $request->getSession()->set('filter', $form->getData());
            }
            if($form->getData()['redirect']){
                return $this->redirect($form->getData()['redirect']);
            }
        }


        $pagination = $this->paginator->paginate(
            $this->em->getRepository(Play::class)->getQueryBuilderByFilter($request->getSession()->get('filter', []))->getQuery(),
            $page ?? 1,
            30
        );
        return $this->render('Frontend/Collection/all.html.twig', [
            'page' => $pagination,
            'filter' => $request->getSession()->get('filter', [])
        ]);
    }

    /**
     * @Route("/pin/{id}")
     */
    public function pin(Request $request ,Play $play){
        $session = $request->getSession();
        $playfav = $session->get('playfav', []);
        if(!isset($playfav[$play->getId()])){
            $playfav[$play->getId()] = $play->getId();
        }
        $session->set('playfav', $playfav);
        $this->addFlash('notice', 'Jeu '. $play->getName() .' ajouté aux favoris');
        return $this->redirect($request->headers->get('referer'));
    }

    /**
 * @Route("/unpin/{id}")
 */
    public function unpin(Request $request ,Play $play){
        $session = $request->getSession();
        $playfav = $session->get('playfav', []);
        if(isset($playfav[$play->getId()])){
            unset($playfav[$play->getId()]);
        }
        $session->set('playfav', $playfav);
        $this->addFlash('notice', 'Jeu '. $play->getName() .' supprimé des favoris');
        return $this->redirect($request->headers->get('referer'));
    }

    /**
     * @Route("/unpinall")
     */
    public function unpinall(Request $request){
        $session = $request->getSession();
        $session->set('playfav', []);
        $this->addFlash('notice', 'Liste vidé');
        return $this->redirect($request->headers->get('referer'));
    }

    /**
     * @Route("/show/{id}", name="play")
     */
    public function play(Request $request)
    {
        return $this->render('Frontend/Default/show.html.twig', [
            'play' => $this->em->getRepository(Play::class)->find($request->get('id'))
        ]);
    }

    /**
     * @Route("/contact", name="contact")
     */
    public function contact(Request $request, \Swift_Mailer $mailer)
    {
        $form = $this->createForm(ContactType::class);
        $form->add('Envoyer', SubmitType::class,[]);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $data = $form->getData();
            $message = new \Swift_Message('Nouveau message de '. $data['email'], $data['message']);
            $message->addFrom($this->getParameter('mailer_from'));
            $message->addTo($this->getParameter('mailer_to'));
            $message->addCc($this->getParameter('mailer_to_cc'));
            $mailer->send($message);
            $this->addFlash('notice', 'Message envoyé');
        }
        return $this->render('Frontend/Default/contact.html.twig', [
            'form' => $form->createView()
        ]);
    }

    public function filter(Request $request){
        $form = $this->createForm(PlayFilterType::class,  $request->getSession()->get('filter', []));
        return $this->render('Frontend/Default/_filter.html.twig', ['form' => $form->createView()]);
    }

    public function favoris(Request $request){
        return $this->render('Frontend/Default/_favoris.html.twig' , [
            'plays' => $this->em->getRepository(Play::class)->findIn($request->getSession()->get('playfav', []))
        ]);
    }
}

project/templates/Frontend/Default/_favoris.html.twig
{%  if plays|length %}
<strong><i class="fas fa-flag"></i> Liste de jeux "flaggé" (cliquer sur <i class="far fa-flag"></i>)</strong> | <a href="{{ path('app_frontend_default_unpinall') }}">Tout vider</a><br/>
<ul class="list-group">
{% for play in plays %}
    {%  if play.pictur %}
        {%  set img =  ('/uploads/play/' ~play.pictur)|imagine_filter('home_play') %}
    {%  else %}
        {%  set img ='/images/logo.png'|imagine_filter('home_play') %}
    {%  endif %}
    <li class="list-group-item">
            <div class="pull-left">
                <a style="height:50px" href="{{  path('app_frontend_default_unpin', {'id':play.id}) }}"><i class="fa fa-trash"></i></a>&nbsp;
                <a style="height:50px" href="{{  path('play', {'id':play.id}) }}"><i class="fa fa-eye"></i> {{ play.name }}</a><br/>
                <label>Nombre de joueurs :</label>  {{ play.nbPlayer }}<br/>
                <label>À partir de : </label> {{ play.age }} ans
            </div>
            <img class="pull-right"  style="height:50px" src="{{ img }}"/>
        {#{% if play.logo %}<img class="pull-right"  src="{{  ('/uploads/playlogo/'~play.logo)|imagine_filter('logo_play_fav') }}"/>{%  endif %}
            <img class="pull-right" style="height:50px;" src="/uploads/editor/{{ play.editor.logo }}"/>#}

        <div style="clear: both;"></div>
    </li>
{%  endfor %}
</ul>
{%  endif %}

project/templates/Frontend/Default/_filter.html.twig
{% form_theme form with ['Frontend/Form/filter.html.twig']  %}
{{ form(form) }}

project/templates/Frontend/Default/_flash.html.twig
{% for flashMessage in app.session.flashbag.get('error') %}
    <div class="lego-flash alert alert-danger alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h4><i class="icon fa fa-ban"></i>{{ 'lego.flash.error'|trans }}</h4>
        {{ flashMessage|raw }}
    </div>
{% endfor %}

{% for flashMessage in app.session.flashbag.get('warning') %}
    <div class="lego-flash alert alert-warning alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h4><i class="icon fa fa-warning"></i>{{ 'lego.flash.warning'|trans }}</h4>
        {{ flashMessage|raw }}
    </div>
{% endfor %}

{% for flashMessage in app.session.flashbag.get('info') %}
    <div class="lego-flash alert alert-info alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h4><i class="icon fa fa-info"></i>{{ 'lego.flash.info'|trans }}</h4>
        {{ flashMessage|raw }}
    </div>
{% endfor %}

{% for flashMessage in app.session.flashbag.get('notice') %}
    <div class="lego-flash alert alert-success alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h4><i class="icon fa fa-check"></i>{{ 'lego.flash.success'|trans }}</h4>
        {{ flashMessage|raw }}
    </div>
{% endfor %}

project/templates/Frontend/Default/_note.html.twig
{%  if good is not defined %}{%  set good = '#000' %}{%  endif %}
{%  if bad is not defined %}{%  set bad = '#ccc' %}{%  endif %}
{%  for i in 1..4 %}
    {% if note > i-1 and note < i %}
        <span class="fa fa-star-half-alt" style="color:{{  good }};"></span>
    {% else %}
        <span class="fa fa-star" style="color:{%  if note >= i %}{{  good }}{% else %}{{ bad }}{%  endif %};"></span>
    {%  endif %}
{%  endfor %}

project/templates/Frontend/Default/contact.html.twig
{% extends 'Frontend/base.html.twig' %}


{%  form_theme form 'bootstrap_4_layout.html.twig' %}
{% block body %}
    <style>
        textarea{
            height:400px !important;
        }
    </style>
    {{ form(form) }}
{%  endblock %}

project/templates/Frontend/Default/show.html.twig
{% extends 'Frontend/base.html.twig' %}

{% block body %}
    <div class="row">
        <div class="col-md-12">
            <h1>{%  if play.logo %}<img src="{{ ('/uploads/playlogo/' ~play.logo)|imagine_filter('h_logo_play') }}"/>{%  else %}{{ play.name }}{%  endif %}
                <div class="pull-right">
                    {% if play.editor %}<img style="height:50px;" src="/uploads/editor/{{ play.editor.logo }}"/>{%  endif %}
                </div>
            </h1>
            <hr/>

        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="pull-left">
            {%  if play.pictur %}
                <img src="{{ ('/uploads/play/' ~play.pictur)|imagine_filter('home_play') }}" class=" vignette"/>
            {%  else %}
                <img src="{{ '/images/logo.png'|imagine_filter('home_play') }}" class=" vignette"/>
            {%  endif %}
            </div>
            <div class="pull-left" style="padding-left:10px;">
                <label>Nombre de joueurs :</label>  {{ play.nbPlayer }}<br/>
                <label>À partir de : </label> {{ play.age }} ans<br/>
                <label>Editeur : </label> {{ play.editor }}<br/>
                <label>Note : </label> <span>{% include 'Frontend/Default/_note.html.twig' with {'note': play.noteAverageAll} %}</span><br/>
                <label>Durée : </label>&nbsp;<span class="label label-primary"><i class="fas fa-hourglass-half"></i>&nbsp;{{  play.duration }}</span><br/>
                <label>Genres : </label> {%  for genre in play.genres %}<span class="label label-success">{{ genre }}</span>&nbsp;{%  else %}<span class="label label-success">Aucun</span>&nbsp;{%  endfor %}
            </div>
            <div class="pull-left" style="padding-left:10px;">
                <label>Nombre de joueurs conseillés :</label>  {{ play.nbPlayerAdvisor }}<br/>
                {% if play.requirement %}<label>Nécessite : </label> <a href="{{ path('play', {'id': play.requirement.id}) }}">{{ play.requirement.name }}</a><br/>{%  else %}<br/>{%  endif %}
                <br/><br/><br/><br/>
                <label>Thèmes : </label> {%  for theme in play.themes %}<span class="label label-warning">{{ theme }}</span>&nbsp;{%  else %}<span class="label label-warning">Aucun</span>&nbsp;{%  endfor %}<br/>
            </div>

        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <hr/>
            <h3><i class="fas fa-thumbtack"></i>&nbsp;Description du jeu :</h3>
            {{ play.description|raw }}
            <hr/>
            <h3><i class="fas fa-clipboard-list"></i>&nbsp;Extensions du jeu :</h3>
            <ul style="margin: 0px; list-style-type: none;">
            {%  for ext in play.extensions %}
                <li><a href="{{ path('play', {'id': ext.id}) }}"><i class="fas fa-link"></i>&nbsp;{{ ext.name }}</a></li>
                {%  for e in ext.extensions %}
                    <li><a href="{{ path('play', {'id': e.id}) }}"><i class="fa fa-link"></i>&nbsp;{{ e.name }}</a> (de {{ ext.name }})</li>
                {%  endfor %}
            {%  else %}
                Aucune extension
            {%  endfor %}
            </ul>
        </div>
    </div>

    <div class="row" >
        <div class="col-md-12"><hr/>
            <h3><i class="fas fa-save"></i>&nbsp;Fichiers :</h3>
            {{ lgo_list_attachment(play, {"icon": "far fa-file"}) }}
        </div>
    </div>


    <div class="row" style="margin-bottom:20px;">

            <div class="col-md-12"><hr/>
                <h3><i class="fab fa-rocketchat"></i>&nbsp;Note et avis des joueurs :</h3>
            </div>
            {%  for comment in play.playComments|merge(play.players) %}
            <div class="col-md-4">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <i class="fas fa-skull"></i>
                        <strong>{{ comment.player }}</strong> le {{ comment.updatedAt|date('d/m/Y') }}
                        <div class="pull-right">
                            {% include 'Frontend/Default/_note.html.twig' with {'note': comment.note} %}
                        </div>
                    </div>
                    <div class="panel-body">
                        {{ comment.message|raw }}
                    </div>
                </div>
            </div>
            {% else %}
                <div class="col-md-12"><ul>Aucun commentaire</ul></div>
            {%  endfor %}
    </div>
{%  endblock %}

{% block rightbar %}
    {%  if play.video %}
        {% include 'Frontend/Collection/_video.html.twig' with {'video':play.video} %}
    {%  endif %}
{%  endblock %}
{%  block js %}<script>$('#mainmenu ul li').removeClass('active'); $('#menu-play').addClass('active');</script>{%  endblock %}